### ISSUE TITLE
Name handling and bugs

### ISSUE THREAD

**Issue by soluxima-erik** [owncloud/contacts#1036]
**Bug:** Modifying the name by clicking on the pencil and then editing the unfolded individual name fields does not update the combined name field after folding again. Editing both is required (I fail to see why have 2 systems).

**Bug:** Adding only a name in the combined name field does not split them into first and last. This should either be forced on the inputting user for verification or just split by word spaces. Currently when saving, on synced devices the name shows up as "First Last;;;" until manually edited to correct.

**Feature request:** There are no fields for prefixes or suffixes. (VCARD3 standard does have these fields as standard) Can we get these fields available if needed? We have some Dr.'s and II's in our contacts. 
```N*:name (semicolon separated: LASTNAME; FIRSTNAME; ADDITIONAL NAME; NAME PREFIX(Mr.,Mrs.); NAME SUFFIX) (*required)```

**Comment by gvde** [comment]
1. Don't mix multiple bugs and features requests into one issue. One bug=one issue. Otherwise it gets really confusing...

2. Always first search existing issues and pull requests for solutions. The second bug has been reported multiple times. It's probably a duplicate of #986 for which there is PR #999.

3. Always use the template from the [contribution guidelines](https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md)

**Comment by soluxima-erik** [comment]
@gvde .. yes sir.
I did see that PR, but it seamed to be about new imports and there was a fix referenced I could not figure out.
We are using a commercially hosted version of OC so I will work with that tech team on these issues. I just figured to post my 2 cents to the community about an otherwise amazing piece of software.

**Comment by gvde** [comment]
You are confusing #1032 and #999. #999 is not about the import. #1032 is. Two different issues with two different fixes even though they result in the same bogus N value...
And again: your 2 cents are welcome but mixing various suggestions/bugs in a single issue is just confusing.
