### ISSUE TITLE
Where is issue 1058?

### ISSUE THREAD

**Issue by WolfgangFahl** [owncloud/contacts#219]
https://forum.owncloud.org/viewtopic.php?t=29982 points toi issue 1058 but the link is broken. The problem on El Capitan seems not to have been fixed so I am wondering which issue tracks it.

**Comment by DeepDiver1975** [comment]
The link on the forum should be updated to https://github.com/owncloudarchive/contacts/issues/1058

**Comment by WolfgangFahl** [comment]
Thanks for the pointer that is helpful. What i do not get is: that issue is not closed. So why is this issue closed that points out that the problem persists? As it looks there would at least be a workaround available that could be mentioned here. The link in the apple discussion board https://discussions.apple.com/thread/7256481?start=0&tstart=0 is also broken which makes it hard for this problem to get properly fixed on the Apple side.

**Comment by DeepDiver1975** [comment]
owncloudarchive/contacts#1058 is not closed because it most probably still persists - TBH: it will not be fixed I guess sine the old contacts app is unmaintained for years and we dropped it with oc9.

oc9 comes with a new implementation of the caldav and carddav interface which lives in core.
feel free testing the new caldav and carddav endpoints with mac osx - in case you find issues - please open a ticker in the core repo.

Hopefully this puts some more light into this area. THX

**Comment by WolfgangFahl** [comment]
The issue is not about the contacts app but about the carddav interface. The problem with El Capitan's addressbook persists af of oc9. On a test with Mac OS 10.11.3 contacts version 9.0 build 1679.4
entering username, password, server address and serverpath as it would work on a Mac OS mavericks will fail with "accountname/password" could not be verified.

**Comment by DeepDiver1975** [comment]
> The issue is not about the contacts app but about the carddav interface.

yes - this is what I was explaining above and therefore this has to be reported in the core repo.

**Comment by ghost** [comment]
@WolfgangFahl As stated quite often in https://github.com/owncloudarchive/contacts/issues/1058 this is not an issue within ownCloud but within El Capitan itself (Ref: https://github.com/owncloudarchive/contacts/issues/1058#issuecomment-195424801, https://github.com/owncloudarchive/contacts/issues/1058#issuecomment-190169043 and some more)

There is nothing to fix from ownCloud side here (except maybe: https://github.com/owncloud/core/issues/22941) so this also doesn't need to be reported in the core repo. From user-side the only thing what you can do is to try: https://doc.owncloud.org/server/9.0/admin_manual/issues/general_troubleshooting.html#service-discovery to work around the bug in the account setup of Apple and hope they fix this

**Comment by Schlumpfpapa** [comment]
Most off the above links are not working any more. This makes it very difficult to understand what the problem with owncloud and El Captian and Sierra is, because it still remains unsolved by Apple.

**Comment by j-holub** [comment]
I have a similar issue.

It didn't work then after hours of trial & error (since CardDav things aren't really documented anymore in the OC documentation) I managed to get it to work again.

Then suddenly one day half of my contacts were gone. Now I deleted the account and fail again the recreate it in a way that works.
