### ISSUE TITLE
Split Contact Details into two colums

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#354]
Otherwise, i think that it looks strange on larger screens :grin: 

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yes, definktely. We had that in the old app too. We can for sure put the big address blocks in the second column, then it's also consistent.

**Comment by skjnldsv** [comment]
Agreed!
Like this?
![contacts owncloud](https://cloud.githubusercontent.com/assets/14975046/14585423/15c88176-0475-11e6-87c3-c3b5bf8cd7fe.png)

**Comment by aspdye** [comment]
Oh no ... It was about the Details (phone, adress, ...) we want to split :grin:

**Comment by skjnldsv** [comment]
Okay, I need to learn to read again...
Well, looked fun anyway :D

**Comment by jancborchardt** [comment]
LOL :D Yeah, definitely not two rows of contacts.

**Comment by skjnldsv** [comment]
![capture d ecran_2016-05-14_11-56-05](https://cloud.githubusercontent.com/assets/14975046/15267762/db8c5378-19ca-11e6-928e-77343b8c3bef.png)

Like this?
This needs a lot of work, and fix _(jan, stop using absolute positionning, it's everywhere !!!!)_ But it's working great :)

**Comment by aspdye** [comment]
Great work :rocket: That was exactly what i have meant.

**Comment by jancborchardt** [comment]
@skjnldsv nice! Just a few things:
- a bit more whitespace between the columns would be good
- I would put the one-liner stuff on the left (email, phone, etc) and the multiline post address on the right, so that it’s balanced

**Comment by skjnldsv** [comment]
Yes, I haven't had the time to continue my work on it these days! :( 
I should be available soon. :)

**Comment by manishbisht** [comment]
@jancborchardt @skjnldsv @aspdye @DeepDiver1975
Hi, I am working on this issue. I have split the contact details section into 2 columns if the screen width is greater then 1200px.

Now by default only 3 fields i.e Phone, Email and Address are shown and after splitting into 2 columns there is more empty space shown in the contact details section which looks bad.

Now how can I display the more fields like Website, Nickname, Notes etc using ng-repeat in the contact details section or the other way to display more fields will be to call the ctrl.addFiled(field) function.

Also I want to know that what parameters does the ctrl.addFiled function accepts.

**Comment by jancborchardt** [comment]
What is very important regarding layout:
- use 2 columns, and not more!
- left column is phone, email address etc
- right column is addresses
- have enough whitespace between the columns

**Comment by manishbisht** [comment]
@jancborchardt 
- Only 2 columns will be displayed on screen size larger than 1200px [Implemented]
- left column is phone, email, address etc [By default Implemented]
- right column is addresses [Can be Implemented Easily](What I have think of is to display the other fields like Website, Social, Note etc instead of showing the repeated field address)
- have enough whitespace between the columns (Can be fixed once the above point is implemented)

**Comment by skjnldsv** [comment]
@manishbisht I was already working on this see #411 :)
If you want to inspire from it, feel free!

**Comment by irgendwie** [comment]
Closing in favor of #505

**Comment by DeepDiver1975** [comment]
I'm reopening this issue because there is a bounty on this issue. #505 will be closed - here is the specification:

Since #480 the contacts app shows the contact details in a two column list, if screen size is >= 1450px. It makes use of the ['CSS3 Multiple Columns' Feature](http://www.w3schools.com/css/css3_multiple_columns.asp). This has the advantage of being less error-prone but comes with a few minor disadvantages:
- The columns are always balanced, meaning address fields, detailed name, etc. may get split
- The balance can lead to (minor) visual issues when using padding (as identified by @skjnldsv):
  ![hzplsn6](https://cloud.githubusercontent.com/assets/8360698/18181937/f5f01e2e-708d-11e6-8f02-96163d27a9bc.gif)
- ...

As suggested by @jancborchardt in #354, what was done by now:

> What is very important regarding layout:
> - [X] use 2 columns, and not more!
> - [ ] left column is phone, email address etc
> - [ ] right column is addresses
> - [X] have enough whitespace between the columns

**Comment by snaiperskaya96** [comment]
So basically the issue is now about splitting details between the two columns even if they become unbalanced and fix the visual issue?

**Comment by william-weber** [comment]
<img width="882" alt="screen shot 2017-06-30 at 10 39 21 am" src="https://user-images.githubusercontent.com/1109049/27748217-6d88c624-5d83-11e7-92b1-6863f78afc62.png">
Here's what it looks like on large screens. I checked for jumping issues/glitches when resizing and didn't see any.
