### ISSUE TITLE
Mobile styles

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#36]
We need to copy over the mobile styles from the Mail app so contacts properly works on small screens.

**Comment by tomneedham** [comment]
What's the plan for the layout, right now I get this: 
![screen shot 2016-02-18 at 14 24 59](https://cloud.githubusercontent.com/assets/660805/13145978/75f519ae-d64b-11e5-8204-0fa421e60294.png)

**Comment by jancborchardt** [comment]
@tomneedham if you want to take a stab at this, check out the Mail app. Essentially you can copy the mobile.css from there, of course with class name adjustments.

**Comment by jancborchardt** [comment]
What should happen is:
- by default, the contact list shows, with the sidebar button on the top left (like now)
- tapping a contact opens the detail view
- the detail view looks like now, but has a back button to go back to the contact list

**Comment by tomneedham** [comment]
** tries mail app _again_ ** ;-)

**Comment by tomneedham** [comment]
See IRC: #owncloud-contacts please :)

**Comment by skjnldsv** [comment]
Should I suggest this? :)
![contacts owncloud](https://cloud.githubusercontent.com/assets/14975046/14103142/e64ceed0-f59e-11e5-8a03-d08b50d29100.png) ![contacts owncloud2](https://cloud.githubusercontent.com/assets/14975046/14103141/e64c5e02-f59e-11e5-8e2f-e5ce3edf3b88.png)

Instead of this:
![contacts owncloud3](https://cloud.githubusercontent.com/assets/14975046/14103146/e95b8fd2-f59e-11e5-8979-11911c609de3.png)

**Comment by skjnldsv** [comment]
Okay, just saw that's exaclty what  @tomneedham  did in the PR, good job! ;)

**Comment by jancborchardt** [comment]
@skjnldsv yeah dude, and additionally your replacing of the menu button with the back button in the details view is great! :)

**Comment by skjnldsv** [comment]
Eheh
