### ISSUE TITLE
Enhancement: Contacts Actions

### ISSUE THREAD

**Issue by h43mxyz** [owncloud/contacts#407]
I want to request a couple of enhancements for the app if possible, I my opinion can be usefull.

Link actions anchors like the one used in website field for the phone and email fields, so we can click on them and perform desired action and use this app as a proper contact app in mobile devices for example.

For the phone field: 
`<a ng-if="ctrl.data.value.length" class="phone-link ng-scope" target="_blank" href="telf:123456789"></a>`

For the email field: 
`<a ng-if="ctrl.data.value.length" class="email-link ng-scope" target="_blank" href="mailto:oc@owncloud.com"></a>`

Thank you.

**Comment by DeepDiver1975** [comment]
Mind submitting a PR? Thanks alot!

**Comment by Rello** [comment]
in the GUI, the fields are input-fields due to its in-line-editing functionality.
adding an <a> would not help here.
`<input type="text" id="details-email" name="email" ng-model="ctrl.data.value" ng-model-options="{ debounce: 500 }" ng-change="ctrl.model.updateContact()" value="" placeholder="E-Mail" focus-expression="$parent.ctrl.focus === ctrl.name" class="ng-pristine ng-valid ng-scope ng-not-empty ng-touched">`

Adding an on-click-event is difficult because this is what the editing does.
An alternative would be action buttons next to the field (next to the trash) in case it is a field where its possible.

thoughts?

**Comment by diesl** [comment]
I think this is a duplicate of #198.

> in the GUI, the fields are input-fields due to its in-line-editing functionality.

This could be solved with a view/edit mode as mentioned in another issue. Right now, the app is mainly focused on editing contacts, but not on viewing/using them.

**Comment by william-weber** [comment]
<img width="423" alt="screen shot 2017-06-30 at 12 34 30 pm" src="https://user-images.githubusercontent.com/1109049/27751494-78566472-5d91-11e7-96c2-ec67230b8188.png">
How does this look? Implementation is the same as the Web link, just different icons.
