### ISSUE TITLE
Contact groups/categories are stored wrongly

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/contacts#433]
### Steps to reproduce
1. Create a contact
2. Assign multiple groups
3. Check the VCard that is sent to the server
### Expected behaviour

Expected: `CATEGORIES:1,2`
### Actual behaviour

Actual: `CATEGORIES:1\,2`

So the `,` is escaped causing the value to be interpreted as one group called `one-slash-comma-two` instead of two groups `one` and `two`

**Comment by nickvergessen** [comment]
Ref https://github.com/owncloud/core/issues/25030#event-686992296

**Comment by DeepDiver1975** [comment]
thx @nickvergessen

**Comment by carlomorgenstern** [comment]
same thing happens with the "TYPE" property, which makes basically every vcard exported from owncloud invalid for me.

Steps to reproduce
1. Create a contact
2. Insert a parameter with the "TYPE" property (e.g. a work phone number)
3. Check the VCard

Expected: `TEL;TYPE=WORK,VOICE:xxxxxx`
Actual: `TEL;TYPE=WORK\,VOICE:xxxxxx`

**Comment by j-ed** [comment]
ownCloud version: 9.0.4
Contacts app version: 1.4.0.0

```
> Expected: TEL;TYPE=WORK,VOICE:xxxxxx
> Actual: TEL;TYPE=WORK\,VOICE:xxxxxx
```

I can confirm that this issue causes problems when synchronize phone number types from ownCloud to Android using e.g. the "ContactSync - CardDAV und mehr" app. I had a discussion with the app developer and she confirmed that the escaped comma is causing the problem and that this need to be fixed in ownCloud.

**Comment by irgendwie** [comment]
jfr. This issue is caused by our vcard parser:
https://github.com/Heymdall/vcard

**Comment by j-ed** [comment]
@irgendwie  If the root cause has been identified half way of a fix has already been done ;-)
Let me know if anything should be tested, I'm usually synchronizing data to an Android phone and iPhone.
(**BTW:** wouldn't it be possible to provide pre-compiled test releases. This would make testing of individual fixes much easier)

**Comment by xenji** [comment]
FYI: https://github.com/Heymdall/vcard/pull/6

**Comment by derqurps** [comment]
@xenji is the pull request only intended for the TYPE field or also for the groups/categories fields? If not, should i do another one for these fields?

**Comment by xenji** [comment]
@derqurps Due to https://github.com/Heymdall/vcard/pull/6/files?diff=unified#diff-d44c6e34337aec12784cda75e6a8a40aR245 it only targets the `TYPE` field. Other field should be easy to add in this if / else construct. Although I think there are better ways to solve this from the architectural perspective (delegation / strategy), than the way I did.

**Comment by xenji** [comment]
FYI: My patch in the vcard lib has been merged upstream.
