### ISSUE TITLE
Download icon for .vfc does not appear

### ISSUE THREAD

**Issue by MariusBluem** [owncloud/contacts#476]
### Expected behavior

Download icon for .vfc does appear
### Actual behavior

It doesn't 😒 
<img width="714" alt="hello" src="https://cloud.githubusercontent.com/assets/19711361/17292360/d5caaee6-57e9-11e6-952c-428def1efba4.png">
### Server configuration

**ownCloud version:** (see ownCloud admin page)
Nextcloud 9.0.53
**Contacts version:** (see ownCloud apps page)
1.3.1
### Client configuration

**Browser:**
Firefox, Safari
**Operating system:**
OS X El Capitan

Disussed and reproduced with @jancborchardt

**Comment by DeepDiver1975** [comment]
there is an sabre dav plugin necessary to allow this operation - this was introduced with owncloud 9.0.2
https://github.com/owncloud/core/pull/23897 - maybe something missing on the nc server side

this is not an issue of the contacts app -> closing

**Comment by LukasReschke** [comment]
@DeepDiver1975 Thanks for your feedback. 

I would greatly appreciate if you could spend a bit more time before closing an issue. It's otherwise  contra-productive and only makes all participants feel bad.

The download button is also missing on ownCloud. I have just taken the time to install ownCloud 9.0.4. It is also not appearing there:

![2016-08-01_15-58-49](https://cloud.githubusercontent.com/assets/878997/17296312/d9e6ba08-5800-11e6-8188-28853b7c7a53.png)

So this seems to be a bug that also affects the ownCloud 9.0.x range.

**Comment by DeepDiver1975** [comment]
backport to stable9 is missing - https://github.com/owncloud/core/pull/23891

**Comment by DeepDiver1975** [comment]
And again - not a contacts issue - but in core -> close.
