### ISSUE TITLE
Range of birthday year is limited

### ISSUE THREAD

**Issue by apo2804** [owncloud/contacts#914]
I've tried to set a date like 1955-06-10, but the date picker limits the option of the year (like shown in the screenshot). If i try to enter the date directly i get no error, but the old date get show instead.

My installation is based on:
apache 2.4
MariaDB 10
Owncloud 8.0.3

Like posted here: https://forum.owncloud.org/viewtopic.php?f=31&t=28636

**Comment by mckayn** [comment]
I'm facing the same problem.
## Steps to reproduce
1. Editing a Custom Adress Book
2. Adding field Birthday (Geburtstag)
3. I can choose a year max. back to 2005

### Expected behaviour
I'd like to add a year in the 70ies

### Server configuration
**Kail Arm 1.1.0 (debian wheezy port) Vanilla Pkgs.**:

**Apache2.2.22**

**Database:**
Mysql Server 5.4.39
**PHP version:**
5.4.39 with apc cache

**ownCloud version:** (see ownCloud admin page)
8.0.3.4 (from Suse Repo)

**Updated from an older ownCloud or fresh install:**
Fresh
**List of activated apps:**
Activity
Bookmarks
Calendar
Contacts
Deleted Files
Documents
File Locking
First Run Wizard
Mail Template Editor
OwnNote
Pictures
Provisioning Api
Share Files
Text Editor
Versions
Video Viewer
**The content of config/config.php:**

```
﻿<?php
$CONFIG = array (
  'instanceid' => 'oc521e0envo2',
  'passwordsalt' => '[.]',
  'secret' => '[.]',
  'trusted_domains' =>
  array (
    0 => '[.] hostname',
    1 => '[.] ip',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://[...]',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => '[.]',
  'dbuser' => '[.]',
  'dbpassword' => '[.]',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No (At least not the File Encryption App:)
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by mckayn** [comment]
Thanks for the patch. Now I can put in the correct year. Its not choosable from menu though:
The year will be shown as 199

**Comment by DeepDiver1975** [comment]
> Thanks for the patch. Now I can put in the correct year. Its not choosable from menu though:
> The year will be shown as 199

thanks for testing @mckayn - can you paste screenshot of that issue? THX

**Comment by DeepDiver1975** [comment]
@mckayn please open a new issue for the last remaining topic - THX
